name: PyLint

on: [push, pull_request]

jobs:
    test:
        environment: CI
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - name: Set up Python 3.9
          uses: actions/setup-python@v1
          with:
              python-version: 3.9
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              pip install pylint
        - name: Analysing the code with pylint
          run: |
              pylint . --rcfile=.pylintrc
        - name: update Docker image
          if: ${{ github.event_name == 'push' || github.event.pull_request.merge }}
          env:
            DOCKER_USERNAME: 'starboy369'
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
              sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              sudo docker build --tag starboy369/personal_recommendations_app .
              sudo docker push starboy369/personal_recommendations_app